### ISSUE TITLE
Cannot read property 'lib' of undefined

### ISSUE THREAD

**Issue by vipertechofficial** [virtualeconomy/js-vsys#73]
## Description

At import of the development the kit in node, when running babel compilation, the console tells me there is an error `Cannot read property 'lib' of undefined` and it comes from crypto-js module that should be used as : 

```
import encUtf8 from "crypto-js/enc-utf8"
import AES from "crypto-js/aes";

//... https://github.com/virtualeconomy/js-vsys/blob/8bdac02c3c10cf2b7e78ae40726ab1d80c8b2290/src/utils/hashes.js

export function aesEncrypt(data, key) {
  return AES.encrypt(data, key).toString();
}

/**
 * aesDecrypt decrypts the given data encrypted by AES.
 * @param {string} data - The data to decrypt.
 * @param {string} key - The key used to decrypt data.
 * @returns {string} The decryption result.
 */
export function aesDecrypt(data, key) {
  return AES.decrypt(data, key).toString(encUtf8);
}

```

as it is suggested in documentation when using it in the browser (see https://github.com/codesandbox/codesandbox-client/issues/6140 for precise explanation). Also it ensure smaller object import...

Could someone test the solution out then publish the npm package update? (For such small edit I might not have time to set up everything) THANKS

**Comment by josephzxy** [comment]
Thanks @vipertechofficial !
js-vsys@0.2.2` which includes the proposed improvement has been published.
