### ISSUE TITLE
Optional Seed validation and generation, splitting dictionary to another npm module?

### ISSUE THREAD

**Issue by vipertechofficial** [virtualeconomy/js-vsys#74]
## Description

Does making seed validation optional/additional and splitting dictionary elsewhere on npm so we can use bip39 npm module too is ok?

Maybe a kind of `{min: "8", max: "16", dictionary: Array.of("1", "yolo", "cuz", "idk")}` Object to which dictionary can be loaded separately would save some bytes and ms loading time in client side which I am terribly fighting like if they were potential terror/chaos darkside agents for mobile device for performance... 

https://github.com/bitcoinjs/bip39

# How it matters for performances ?

Here on a project that doesn't use the vsystems API, we have translation file getting loaded as chunks only if needed `const import_en = async() => { return import(`../locales/en`)};` see :
https://github.com/pixa-pics/pixa-pics.github.io/blob/main/src/js/utils/t.js

And with some webpack configuration we achieve to split JS into chunks loading as such : 
![Screenshot from 2022-07-13 19-08-08](https://user-images.githubusercontent.com/74778466/178791100-d42e53a0-3ccd-4f7b-a0fc-18290f97c9f5.png)

And when it load chunk_9.min.js it gets the english translation loaded so we achieve to load the page without content shift in 1573ms

**Comment by josephzxy** [comment]
@ncying
